name: base
dependencies:
  - h5py
  - matplotlib
  - numba
  - numpy
  - pip
  - pytest
  - scipy
  - sympy
  - pip:
    # Basic
      - notebook
    # Qiskit
      - pylatexenc
      - qiskit==1.4
      - qiskit-aer
      - qiskit-ibm-provider
      - qiskit-ibm-runtime
      - qiskit-nature
    # Dev
      - fortls
      - pre-commit
      - ruff
      - scalene
      - sphinx
      - sphinx_rtd_theme
    # Other
      - pyscf
